### ISSUE TITLE
Fix prefix in Iframe URLs

### ISSUE THREAD

**Issue by bea92** [densitydesign/placplac#175]
Embedded iframes don't appear when the website is stored on another server. Probably, there is a problem of prefixes.

**Comment by gianpieropa** [comment]
are you sure you are using the last version of the project? This issue was already solved and i am not able to reproduce it anymore. This is a screen of a builded project hosted in the folder /prova with an iframe in the content
![Schermata 2022-08-04 alle 12 30 47](https://user-images.githubusercontent.com/68102511/182826578-1eade7d2-13ca-49b7-87ec-aa8418057f59.png)

**Comment by gianpieropa** [comment]
Open the issue again if you still encounter the problem after updating to the last version
